import { defineCopy } from "@/lib/i18n/copy";

/**
 * AI connection fields shared by first-run setup and Settings: chat and Jev fieldsets,
 * provider Auth panels, model picker notes, connection validation and save failures.
 * Provider/model IDs, protocol names, URLs and environment names are machine values and
 * stay untranslated. Validation and Auth state keep these keys, never rendered text.
 */
export const AI_COPY = defineCopy({
  ko: {
    common: {
      showKey: "키 보기",
      hideKey: "키 숨기기",
      nameLabel: "연결 이름",
      nameHintOptional: "비워 두면 제공자 이름으로 저장해요.",
      nameHintRequired: "연결을 구분할 이름을 입력하세요.",
      modeLegend: "연결 방식",
      modeApi: "API 키",
    },
    chat: {
      legend: "노트 채팅 AI",
      lead: "질문, 최근 대화 기록, 관련 노트 일부를 선택한 제공자에게 보내요. 꺼 두어도 노트, 캡처, 검색, 그래프는 그대로 쓸 수 있어요.",
      environment: "지금은 서버의 기존 Codex 연결을 쓰고 있어요. 저장된 연결을 선택하거나 사용을 끌 때까지 이 연결을 계속 써요.",
      enable: "노트 채팅에 AI 사용",
      namePlaceholder: "예: 개인 OpenAI",
      provider: "제공자",
      modeAuth: "Auth",
      apiKeyOnly: "이 제공자는 API 키 연결만 지원해요.",
      legacyCli: "서버의 기존 CLI 로그인을 계속 써요. 아래에서 다시 로그인하면 이 연결에 저장한 로그인으로 바뀌어요.",
      cliReady: "로그인 파일 확인됨",
      cliMissing: "로그인 필요",
      cliReadyDetail: "CLI와 로그인 파일을 확인했어요. 계정이 유효한지, 모델을 쓸 권한이 있는지는 실제 첫 요청 때 확인해요.",
      cliMissingDetail: "서버에서 CLI 로그인 파일을 찾지 못했어요. 아래에서 다시 로그인하세요.",
      enterpriseDomain: "기업 도메인 (선택)",
      consent: "질문, 최근 대화 기록, 관련 노트 일부를 선택한 제공자에게 보내는 데 동의해요.",
      model: "사용할 모델",
      modelHintAuth: "최신 모델이 먼저 나와요. 계정이나 요금제에 따라 쓸 수 없는 모델도 있어요.",
      modelHintApi: "모델 ID를 직접 입력하세요. 구독 Auth와 유료 API는 쓸 수 있는 모델이 서로 달라요.",
      apiFormat: "API 형식",
      baseUrl: "API 기본 URL",
      baseUrlHint: "API 접두 주소나 선택한 API 형식에 맞는 전체 요청 주소를 입력하세요. Docker 안에서 localhost는 컨테이너 자신을 가리켜요. 호스트에서 실행 중인 서비스는 host.docker.internal이나 접근할 수 있는 내부망 주소를 쓰세요.",
      keyless: "키 없이 동작하는 로컬 엔드포인트",
      apiKey: "API 키",
      apiKeyRetained: "저장된 키가 있어요. 제공자와 기본 주소를 바꾸지 않았다면 비워 두세요.",
      apiKeyCopilot: "일반 GitHub PAT가 아닌 Copilot API용 토큰을 입력하세요. 구독 Auth와는 별개이고, 저장한 뒤에는 다시 볼 수 없어요.",
      apiKeyHint: "유료 API 키는 구독 Auth와 별개예요. 저장한 뒤에는 다시 볼 수 없어요.",
      maxOutputTokens: "최대 출력 토큰 (선택)",
      headers: "추가 헤더 JSON (선택)",
      headerAction: "추가 헤더 처리",
      headerRetain: "기존 헤더 유지",
      headerReplace: "새 헤더로 교체",
      headerClear: "기존 헤더 삭제",
      headersNote: "저장한 헤더 값은 다시 볼 수 없어요. 목적지를 바꾸면 이전 헤더는 자동으로 지워요.",
    },
    jev: {
      legend: "인박스 정리 AI (Jev)",
      lead: "캡처할 때 분류, 태그, 중복 후보를 제안해요. 캡처 제목, 본문 앞 4,000자, 최근 노트 제목과 ID를 선택한 제공자에게 보내요. 채팅 모델과는 별개이고, 꺼 두거나 실패해도 캡처는 그대로 저장돼요.",
      environment: "지금은 서버 환경에 설정된 기존 Jev 연결을 쓰고 있어요. 저장된 연결을 선택하거나 사용을 끌 때까지 이 연결을 계속 써요.",
      enable: "인박스 정리에 Jev 사용",
      namePlaceholder: "예: 업무용 Jev",
      provider: "Jev 제공자",
      providers: { typesafe: "TypeSafe 공식", openrouter: "OpenRouter" },
      modeAuth: "OpenRouter Auth",
      typesafeApiOnly: "TypeSafe는 API 키 연결만 지원해요.",
      model: "사용할 Jev 모델",
      modelHint: "TypeSafe API와 OpenRouter API/Auth는 키와 사용량을 따로 관리해요. Jev Router는 다른 제품이에요.",
      apiKey: "Jev API 키",
      apiKeyRetained: "저장된 키가 있어요. 제공자를 바꾸지 않았다면 비워 두세요.",
      apiKeyHint: "선택한 Jev 제공자가 발급한 키를 입력하세요. 저장한 뒤에는 다시 볼 수 없어요.",
      consent: "캡처 내용과 최근 노트 정보를 선택한 Jev 제공자에게 보내는 데 동의해요.",
    },
    modelNotes: {
      recommended: "권장",
      "account-gated": "일부 계정",
      saved: "저장된 모델",
      unlisted: "목록에 없음",
    },
    auth: {
      intro: {
        default: "제공자 페이지에서 로그인하고, 확인 코드가 나오면 그 페이지에 입력하세요. 비밀번호나 발급받은 토큰은 이 앱에 입력하지 않아요.",
        openai: "ChatGPT 로그인 페이지를 열고 아래 확인 코드를 그 페이지에 입력하세요. 이 앱에는 코드나 비밀번호를 입력하지 않아요.",
        google: "Google 로그인 페이지에서 권한을 허용하면 일회용 인증 코드가 나와요. 코드를 복사해 아래에 붙여 넣으세요. 비밀번호나 발급받은 토큰은 이 앱에 입력하지 않아요.",
      },
      link: {
        default: "로그인 페이지 열기",
        openai: "ChatGPT 로그인 페이지 열기",
        google: "Google 로그인 페이지 열기",
      },
      openRouterNote: "OpenRouter Auth는 API 키를 발급하는 방식이라 OpenRouter 사용 요금을 내야 해요. 다른 서비스의 구독은 가져오지 않아요.",
      userCode: "확인 코드:",
      openaiDeviceHelp: "코드 입력이 막히거나 거부되면 ChatGPT 설정의 보안에서 Codex 기기 코드 로그인을 켜세요. 워크스페이스 계정은 관리자가 허용해야 해요.",
      ready: "로그인을 확인했어요. 이제 연결을 저장하세요.",
      savedWithDomain: "저장된 로그인이 있어요. 제공자나 기업 도메인을 바꾸지 않으면 그대로 남아 있어요.",
      saved: "저장된 로그인이 있어요. 제공자를 바꾸지 않으면 그대로 남아 있어요.",
      waitingCode: "Google 인증 코드를 기다리는 중이에요.",
      checkingCode: "인증 코드를 확인하는 중이에요.",
      waiting: "로그인 완료를 기다리는 중이에요.",
      start: "로그인 시작",
      restart: "다시 로그인",
      retryStatus: "상태 다시 확인",
      cancel: "로그인 취소",
      codeLabel: "Google 인증 코드",
      codeSubmit: "인증 코드 제출",
      codeSubmitting: "코드 확인 중…",
      codeHint: "한 번만 쓸 수 있는 코드예요. 주소(URL) 전체가 아니라 코드만 붙여 넣으세요.",
      errors: {
        needSetupToken: "먼저 32자 이상의 설치 확인 코드를 입력해 주세요.",
        denied: "로그인이 거부됐어요. 다시 시작하세요.",
        expired: "로그인 시간이 만료됐어요. 다시 시작하세요.",
        failed: "로그인을 완료하지 못했어요. 다시 시도하세요.",
        googleFailed: "인증 코드를 확인하지 못했어요. 로그인 시작을 눌러 새 코드를 받으세요.",
        startFailed: "로그인을 시작하지 못했어요.",
        cancelFailed: "로그인 시도를 취소하지 못했어요.",
        codeSendFailed: "인증 코드를 보내지 못했어요. 다시 시도하세요.",
        statusFailed: "로그인 상태를 확인하지 못했어요.",
      },
      codeErrors: {
        missing: "Google 인증 코드를 붙여 넣어 주세요.",
        format: "주소(URL)나 공백 없이 Google 페이지에 나온 인증 코드만 붙여 넣어 주세요.",
        rejected: "인증 코드를 확인하지 못했어요. Google 로그인 페이지에서 새 코드를 받아 붙여 넣으세요.",
      },
    },
    errors: {
      modelFormat: "모델 ID는 영문, 숫자와 . _ : @ ~ / - 기호만 써서 입력해 주세요.",
      authModelRequired: "목록에서 사용할 모델을 선택해 주세요.",
      headersNotObject: "헤더를 JSON 객체로 입력해 주세요.",
      headersTooMany: "추가 헤더는 16개까지 입력할 수 있어요.",
      headersReserved: "예약됐거나 중복된 헤더 이름이 있어요.",
      headersInvalid: "헤더 이름과 값을 확인해 주세요.",
      chatConsent: "질문과 관련 노트를 선택한 제공자에게 보내는 데 동의해 주세요.",
      jevConsent: "캡처 내용과 최근 노트 정보를 선택한 Jev 제공자에게 보내는 데 동의해 주세요.",
      apiKeyOnly: "이 제공자는 API 키 연결만 지원해요.",
      typesafeApiKeyOnly: "TypeSafe는 API 키 연결만 지원해요.",
      browserLoginRequired: "브라우저에서 로그인을 마쳐 주세요.",
      openRouterLoginRequired: "OpenRouter 로그인을 완료해 주세요.",
      baseUrlRequired: "API 기본 URL을 입력해 주세요.",
      baseUrlTooLong: "API 기본 URL은 2,048자까지 입력할 수 있어요.",
      baseUrlInvalid: "올바른 API 기본 URL을 입력해 주세요.",
      baseUrlUnsafe: "인증 정보·쿼리·해시가 없는 HTTP(S) 기본 주소를 입력해 주세요.",
      apiKeyOrKeyless: "API 키를 입력하거나 키 없이 연결하도록 선택해 주세요.",
      apiKeyRequired: "선택한 제공자의 API 키를 입력해 주세요.",
      jevApiKeyRequired: "선택한 Jev 제공자의 API 키를 입력해 주세요.",
      maxOutputTokensRange: "1부터 128000까지의 정수를 입력해 주세요.",
      nameRequired: "연결 이름을 입력해 주세요.",
    },
    save: {
      failed: "AI 설정을 저장하지 못했어요. 다시 시도하세요.",
      network: "서버에 연결하지 못했어요. 네트워크 연결을 확인한 뒤 다시 시도하세요.",
    },
  },
  en: {
    common: {
      showKey: "Show key",
      hideKey: "Hide key",
      nameLabel: "Connection name",
      nameHintOptional: "Leave blank to use the provider name.",
      nameHintRequired: "Enter a name that tells this connection apart.",
      modeLegend: "Connection type",
      modeApi: "API key",
    },
    chat: {
      legend: "Note chat AI",
      lead: "Sends your question, recent conversation and parts of related notes to the provider you choose. Notes, capture, search and the graph keep working without it.",
      environment: "You're using the server's existing Codex connection. It stays on until you pick a saved connection or turn it off.",
      enable: "Use AI for note chat",
      namePlaceholder: "e.g. Personal OpenAI",
      provider: "Provider",
      modeAuth: "Auth",
      apiKeyOnly: "This provider supports API key connections only.",
      legacyCli: "This connection keeps using the server's existing CLI sign-in. Signing in again below switches it to a sign-in saved with this connection.",
      cliReady: "Sign-in file found",
      cliMissing: "Sign-in needed",
      cliReadyDetail: "The CLI and its sign-in file are in place. The first real request checks your account and model access.",
      cliMissingDetail: "Couldn't find the CLI sign-in file on the server. Sign in again below.",
      enterpriseDomain: "Enterprise domain (optional)",
      consent: "I agree to send my questions, recent conversation and parts of related notes to the selected provider.",
      model: "Model",
      modelHintAuth: "Newest models are listed first. Some may not be available on your account or plan.",
      modelHintApi: "Enter the model ID. Subscription Auth and a paid API can offer different models.",
      apiFormat: "API format",
      baseUrl: "API base URL",
      baseUrlHint: "Enter the API prefix, or the full request URL for the selected API format. In Docker, localhost points to the container itself. For services on the host, use host.docker.internal or a reachable internal address.",
      keyless: "Local endpoint that works without a key",
      apiKey: "API key",
      apiKeyRetained: "A key is saved. Leave this blank if you haven't changed the provider or base URL.",
      apiKeyCopilot: "Enter a Copilot API token, not a regular GitHub PAT. It's separate from subscription Auth and isn't shown again after saving.",
      apiKeyHint: "A paid API key is separate from subscription Auth. It isn't shown again after saving.",
      maxOutputTokens: "Max output tokens (optional)",
      headers: "Extra headers JSON (optional)",
      headerAction: "Extra header handling",
      headerRetain: "Keep existing headers",
      headerReplace: "Replace with new headers",
      headerClear: "Remove existing headers",
      headersNote: "Saved header values aren't shown again. If you change the destination, the previous headers are removed automatically.",
    },
    jev: {
      legend: "Inbox triage AI (Jev)",
      lead: "Suggests categories, tags and possible duplicates as you capture. Sends the capture title, the first 4,000 characters of the body, and recent note titles and IDs to the provider you choose. It's separate from the chat model, and captures are still saved if it's off or fails.",
      environment: "You're using the existing Jev connection from the server environment. It stays on until you pick a saved connection or turn it off.",
      enable: "Use Jev for inbox triage",
      namePlaceholder: "e.g. Work Jev",
      provider: "Jev provider",
      providers: { typesafe: "TypeSafe (official)", openrouter: "OpenRouter" },
      modeAuth: "OpenRouter Auth",
      typesafeApiOnly: "TypeSafe supports API key connections only.",
      model: "Jev model",
      modelHint: "TypeSafe API and OpenRouter API/Auth track keys and usage separately. Jev Router is a different product.",
      apiKey: "Jev API key",
      apiKeyRetained: "A key is saved. Leave this blank if you haven't changed the provider.",
      apiKeyHint: "Enter a key issued by the selected Jev provider. It isn't shown again after saving.",
      consent: "I agree to send capture content and recent note details to the selected Jev provider.",
    },
    modelNotes: {
      recommended: "recommended",
      "account-gated": "some accounts",
      saved: "saved",
      unlisted: "not listed",
    },
    auth: {
      intro: {
        default: "Sign in on the provider's page and enter the code there if one appears. You never enter your password or issued tokens in this app.",
        openai: "Open the ChatGPT sign-in page and enter the code below on that page. You don't enter a code or password in this app.",
        google: "Allow access on Google's sign-in page and it shows a one-time authorization code. Copy it and paste it below. You never enter your password or issued tokens in this app.",
      },
      link: {
        default: "Open sign-in page",
        openai: "Open ChatGPT sign-in page",
        google: "Open Google sign-in page",
      },
      openRouterNote: "OpenRouter Auth issues an API key, so you pay OpenRouter usage fees. It doesn't bring over subscriptions from other services.",
      userCode: "Your code:",
      openaiDeviceHelp: "If entering the code is blocked or rejected, turn on device code sign-in for Codex under Security in ChatGPT settings. Workspace accounts need an admin to allow it.",
      ready: "Sign-in confirmed. Save the connection now.",
      savedWithDomain: "You have a saved sign-in. It stays unless you change the provider or enterprise domain.",
      saved: "You have a saved sign-in. It stays unless you change the provider.",
      waitingCode: "Waiting for your Google authorization code.",
      checkingCode: "Checking the authorization code.",
      waiting: "Waiting for you to finish signing in.",
      start: "Start sign-in",
      restart: "Sign in again",
      retryStatus: "Check status again",
      cancel: "Cancel sign-in",
      codeLabel: "Google authorization code",
      codeSubmit: "Submit code",
      codeSubmitting: "Checking code…",
      codeHint: "This code works only once. Paste only the code, not the whole URL.",
      errors: {
        needSetupToken: "Enter the installation code (32 or more characters) first.",
        denied: "Sign-in was denied. Start again.",
        expired: "Sign-in timed out. Start again.",
        failed: "Couldn't finish signing in. Try again.",
        googleFailed: "Couldn't verify the authorization code. Select Start sign-in to get a new code.",
        startFailed: "Couldn't start sign-in.",
        cancelFailed: "Couldn't cancel the sign-in attempt.",
        codeSendFailed: "Couldn't send the authorization code. Try again.",
        statusFailed: "Couldn't check the sign-in status.",
      },
      codeErrors: {
        missing: "Paste your Google authorization code.",
        format: "Paste only the authorization code shown on Google's page, without a URL or spaces.",
        rejected: "Couldn't verify the authorization code. Get a new code from Google's sign-in page and paste it here.",
      },
    },
    errors: {
      modelFormat: "Enter a model ID that uses only letters, numbers and . _ : @ ~ / -",
      authModelRequired: "Choose a model from the list.",
      headersNotObject: "Enter the headers as a JSON object.",
      headersTooMany: "You can add up to 16 extra headers.",
      headersReserved: "A header name is reserved or used twice.",
      headersInvalid: "Check the header names and values.",
      chatConsent: "Agree to send your questions and related notes to the selected provider.",
      jevConsent: "Agree to send capture content and recent note details to the selected Jev provider.",
      apiKeyOnly: "This provider supports API key connections only.",
      typesafeApiKeyOnly: "TypeSafe supports API key connections only.",
      browserLoginRequired: "Finish signing in with your browser.",
      openRouterLoginRequired: "Finish signing in to OpenRouter.",
      baseUrlRequired: "Enter the API base URL.",
      baseUrlTooLong: "The API base URL can be up to 2,048 characters.",
      baseUrlInvalid: "Enter a valid API base URL.",
      baseUrlUnsafe: "Enter an HTTP(S) base URL without credentials, a query or a hash.",
      apiKeyOrKeyless: "Enter an API key, or choose to connect without a key.",
      apiKeyRequired: "Enter an API key for the selected provider.",
      jevApiKeyRequired: "Enter an API key for the selected Jev provider.",
      maxOutputTokensRange: "Enter a whole number from 1 to 128000.",
      nameRequired: "Enter a connection name.",
    },
    save: {
      failed: "Couldn't save AI settings. Try again.",
      network: "Couldn't reach the server. Check your network connection and try again.",
    },
  },
});

type AiSource = (typeof AI_COPY)["ko"];
/** Stable field-validation reason; each has a message in every locale. */
export type ConnectionErrorKey = keyof AiSource["errors"];
/** Stable provider sign-in failure. */
export type AuthErrorKey = keyof AiSource["auth"]["errors"];
/** Stable Google authorization-code problem. */
export type AuthCodeErrorKey = keyof AiSource["auth"]["codeErrors"];
