/** Korean copy for the cited chat surface. Kept in one place so tests never assert prose. */
export const CHAT_COPY = {
  title: "채팅",
  lead: "저장한 노트를 근거로 답합니다. 답변 아래 출처 카드는 실제 노트로 이어집니다.",
  newThread: "새 대화",
  threadsHeading: "대화 목록",
  threadsEmptyTitle: "아직 대화가 없습니다.",
  threadsEmptyDescription: "새 대화를 만들고 노트에 대해 물어보세요.",
  threadsLoadFailed: "대화 목록을 불러오지 못했습니다.",
  threadLoadFailed: "대화를 불러오지 못했습니다.",
  threadNotFound: "대화를 찾을 수 없습니다.",
  retry: "다시 시도",
  back: "대화 목록",
  rename: "이름 바꾸기",
  renameLabel: "대화 이름",
  renameSave: "저장",
  renameCancel: "취소",
  renameFailed: "이름을 바꾸지 못했습니다.",
  delete: "삭제",
  deleteTitle: "대화를 삭제할까요?",
  deleteDescription: "메시지 기록이 함께 사라지며 되돌릴 수 없습니다.",
  deleteConfirm: "삭제",
  deleteFailed: "대화를 삭제하지 못했습니다.",
  deleted: "대화를 삭제했습니다.",
  createFailed: "대화를 만들지 못했습니다.",
  historyEmptyTitle: "첫 질문을 보내 보세요.",
  historyEmptyDescription: "예: 이번 주에 정리한 프로젝트 메모를 요약해 줘.",
  composerLabel: "질문",
  composerPlaceholder: "노트에 대해 물어보기…",
  composerHint: "Enter로 보내고 Shift+Enter로 줄을 바꿉니다.",
  send: "보내기",
  stop: "중지",
  thinking: "관련 노트를 찾는 중…",
  streaming: "답변 작성 중…",
  statusChecking: "채팅 설정을 확인하는 중…",
  statusUnavailableTitle: "AI 채팅이 아직 설정되지 않았습니다.",
  statusUnavailableDescription:
    "서버의 Codex 로그인(CODEX_HOME/auth.json)이 없어 답변을 생성할 수 없습니다. 노트·검색·캡처는 그대로 사용할 수 있습니다.",
  statusCheckFailed: "채팅 설정 상태를 확인하지 못했습니다.",
  statusRecheck: "다시 확인",
  sources: "출처",
  sourceOpen: "노트 열기",
  sourceLabel: (index: number) => `출처 ${index}`,
  userLabel: "나",
  assistantLabel: "답변",
  failedTitle: "답변을 받지 못했습니다.",
  failedDraftKept: "입력한 질문은 아래 입력창에 남겨 두었습니다.",
  partialAnswer: "완료되지 않은 부분 답변",
  resend: "다시 보내기",
  dismiss: "닫기",
  stopped: "답변 생성을 중지했습니다.",
  incomplete: "서버 응답이 완료되기 전에 끊겼습니다.",
  malformed: "서버 응답을 해석할 수 없습니다.",
  network: "서버에 연결할 수 없습니다.",
  unavailable: "채팅 모델이 설정되지 않아 답변을 생성할 수 없습니다.",
  conflict: "이 대화의 답변을 이미 생성하고 있습니다.",
  unknown: "요청을 처리하지 못했습니다.",
} as const;
