import { defineCopy } from "@/lib/i18n/copy";

/** Chat surface copy: Korean source plus English. Kept in one place so tests never assert prose. */
export const CHAT_COPY = defineCopy({
  ko: {
    title: "채팅",
    lead: "저장한 노트를 근거로 답해요. 답변 아래 출처 카드를 누르면 근거가 된 노트가 열려요.",
    newThread: "새 대화",
    threadsHeading: "대화 목록",
    threadsLoading: "대화 목록을 불러오는 중",
    threadsEmptyTitle: "아직 대화가 없어요",
    threadsEmptyDescription: "새 대화를 시작하고 노트에 대해 물어보세요.",
    threadsLoadFailed: "대화 목록을 불러오지 못했어요.",
    conversation: "대화 내용",
    threadLoading: "대화를 불러오는 중",
    threadLoadFailed: "대화를 불러오지 못했어요.",
    threadNotFound: "대화를 찾을 수 없어요.",
    retry: "다시 시도",
    back: "대화 목록",
    rename: "이름 바꾸기",
    renameLabel: "대화 이름",
    renameSave: "저장",
    renameCancel: "취소",
    renameFailed: "대화 이름을 바꾸지 못했어요.",
    delete: "삭제",
    deleteTitle: "대화를 삭제할까요?",
    deleteDescription: "메시지 기록도 함께 사라지고, 되돌릴 수 없어요.",
    deleteConfirm: "삭제",
    deleteFailed: "대화를 삭제하지 못했어요.",
    deleted: "대화를 삭제했어요.",
    createFailed: "새 대화를 시작하지 못했어요.",
    historyEmptyTitle: "첫 질문을 해 보세요",
    historyEmptyDescription: "예: “이번 주에 정리한 프로젝트 노트를 요약해 줘.”",
    composerLabel: "질문",
    composerPlaceholder: "노트에 대해 물어보기…",
    composerHint: "Enter로 보내고 Shift+Enter로 줄을 바꿔요.",
    send: "보내기",
    stop: "중지",
    thinking: "관련 노트를 찾는 중…",
    streaming: "답변 작성 중…",
    statusChecking: "채팅 설정을 확인하는 중…",
    statusUnavailableTitle: "AI 채팅을 아직 설정하지 않았어요",
    statusUnavailableDescription:
      "설정에서 AI 제공자, 연결 방식, 모델을 선택하세요. 노트·검색·캡처는 AI 없이도 그대로 쓸 수 있어요.",
    statusCheckFailed: "채팅 설정을 확인하지 못했어요.",
    statusRecheck: "다시 확인",
    sources: "출처",
    sourceOpen: "노트 열기",
    sourceLabel: (index: number) => `출처 ${index}`,
    imageFallback: "이미지",
    userLabel: "나",
    assistantLabel: "답변",
    failedTitle: "답변을 받지 못했어요",
    failedDraftKept: "입력한 질문은 아래 입력창에 그대로 있어요.",
    partialAnswer: "미완성 답변",
    resend: "다시 보내기",
    dismiss: "닫기",
    stopped: "답변 생성을 중지했어요.",
    incomplete: "서버 응답이 끝나기 전에 끊겼어요.",
    malformed: "서버 응답을 읽지 못했어요.",
    network: "서버에 연결할 수 없어요.",
    unavailable: "채팅 모델을 설정하지 않아 답변을 생성할 수 없어요.",
    conflict: "이 대화에서 이미 답변을 생성하고 있어요.",
    notFound: "이 대화를 찾을 수 없어요.",
    upstreamFailed: "채팅 모델에서 응답을 받지 못했어요.",
    internal: "답변을 생성하지 못했어요.",
    unknown: "요청을 처리하지 못했어요.",
  },
  en: {
    title: "Chat",
    lead: "Answers are based on your saved notes. The source cards under each answer open the notes they came from.",
    newThread: "New chat",
    threadsHeading: "Conversations",
    threadsLoading: "Loading conversations",
    threadsEmptyTitle: "No conversations yet",
    threadsEmptyDescription: "Start a new chat and ask about your notes.",
    threadsLoadFailed: "Couldn't load conversations",
    conversation: "Conversation",
    threadLoading: "Loading conversation",
    threadLoadFailed: "Couldn't load this conversation",
    threadNotFound: "Conversation not found",
    retry: "Try again",
    back: "Back to conversations",
    rename: "Rename",
    renameLabel: "Conversation name",
    renameSave: "Save",
    renameCancel: "Cancel",
    renameFailed: "Couldn't rename the conversation.",
    delete: "Delete",
    deleteTitle: "Delete this conversation?",
    deleteDescription: "Its messages will be deleted too. This can't be undone.",
    deleteConfirm: "Delete",
    deleteFailed: "Couldn't delete the conversation.",
    deleted: "Conversation deleted.",
    createFailed: "Couldn't start a new chat.",
    historyEmptyTitle: "Ask your first question",
    historyEmptyDescription: "For example: “Summarize the project notes I wrote this week.”",
    composerLabel: "Question",
    composerPlaceholder: "Ask about your notes…",
    composerHint: "Press Enter to send, Shift+Enter for a new line.",
    send: "Send",
    stop: "Stop",
    thinking: "Finding related notes…",
    streaming: "Writing an answer…",
    statusChecking: "Checking chat setup…",
    statusUnavailableTitle: "AI chat isn't set up yet",
    statusUnavailableDescription:
      "Choose an AI provider, connection method and model in Settings. Notes, search and capture work the same without AI.",
    statusCheckFailed: "Couldn't check the chat setup",
    statusRecheck: "Check again",
    sources: "Sources",
    sourceOpen: "Open note",
    sourceLabel: (index) => `Source ${index}`,
    imageFallback: "Image",
    userLabel: "You",
    assistantLabel: "Answer",
    failedTitle: "Couldn't get an answer",
    failedDraftKept: "Your question is still in the message box below.",
    partialAnswer: "Incomplete answer",
    resend: "Send again",
    dismiss: "Dismiss",
    stopped: "Stopped generating the answer.",
    incomplete: "The connection closed before the server finished responding.",
    malformed: "Couldn't read the server's response.",
    network: "Can't reach the server.",
    unavailable: "Can't generate an answer because no chat model is set up.",
    conflict: "This conversation is already generating an answer.",
    notFound: "Couldn't find this conversation.",
    upstreamFailed: "The chat model didn't respond.",
    internal: "Couldn't generate an answer.",
    unknown: "Couldn't complete the request.",
  },
});
