export const INBOX_COPY = {
  title: "Inbox",
  empty: "쌓인 캡처가 없어요",
  capture: "캡처",
  promote: "노트화",
  discard: "폐기",
  discardConfirm: "Inbox에서 지울까요?",
  cancel: "취소",
  apply: "제안 적용",
  later: "나중에",
  promoteFail: "승격에 실패했어요",
  discardFail: "폐기에 실패했어요",
  loadFail: "연결에 실패했어요 · 다시",
  retry: "다시",
  ingestFail: "실패",
  ingestConfirm: "확인",
  manualPromote: "제안 없이 노트화",
  fieldTitle: "제목",
  fieldSummary: "요약",
  suggestTags: "제안 태그",
  sourceWeb: "웹",
  sourceShare: "공유",
  sourceApi: "API",
  sourceFile: "파일",
} as const;
