export const CAPTURE_COPY = {
  fab: "캡처",
  ctaInbox: "Inbox에 넣기",
  ctaNote: "노트로 저장",
  urlHint: "URL은 요약만 저장해요",
  mime: "이 형식은 못 받아요",
  size: "100MB를 넘어요",
  networkError: "연결에 실패했어요",
  ingestError: "URL 요약에 실패했어요",
  unauthorized: "다시 로그인해 주세요",
  retry: "다시",
  title: "캡처",
  titleLabel: "제목",
  bodyLabel: "본문",
  urlLabel: "URL (선택)",
  fileLabel: "파일 (선택)",
  modeInbox: "Inbox",
  modeNote: "Note",
  successInbox: "Inbox에 넣었어요",
  successNote: "노트로 저장했어요",
  duplicateTitle: "같은 내용이 있어요",
  merge: "합치기",
  newVersion: "새 버전",
  cancel: "취소",
} as const;
