import { defineCopy } from "@/lib/i18n/copy";

/**
 * Notes workspace copy (list, detail, editor, preview, connections, daily launcher).
 * Stored note titles, bodies, tags, aliases and excerpts are user data and never pass through here.
 */
export const NOTES_COPY = defineCopy({
  ko: {
    loading: "노트를 불러오는 중…",
    retry: "다시 시도",
    openLinkFailed: "연결된 노트를 열지 못했어요.",
    workspace: {
      emptyTitle: "노트를 선택하세요",
      emptyDescription: "왼쪽 목록에서 노트를 열거나 새로 만드세요.",
    },
    list: {
      label: "노트 목록",
      heading: "노트",
      tagline: "생각을 연결하고 다시 찾으세요.",
      newNote: "새 노트",
      searchLabel: "노트 검색",
      searchPlaceholder: "제목이나 내용 검색",
      clearSearch: "검색 지우기",
      viewsLabel: "노트 보기",
      views: { all: "전체", pinned: "고정", archived: "보관", trash: "휴지통" },
      tagsFailed: "태그를 불러오지 못했어요 · 다시 시도",
      tagFilter: "태그",
      allTags: "모든 태그",
      loadFailedTitle: "노트를 불러오지 못했어요",
      loadFailedDescription: "네트워크 연결을 확인한 뒤 다시 시도하세요.",
      trashEmpty: "휴지통이 비어 있어요",
      empty: "표시할 노트가 없어요",
      emptyFiltered: "검색어나 필터를 바꿔 보세요.",
      emptyStart: "새 노트를 만들어 기록을 시작하세요.",
      pinned: "고정됨",
      loadMore: "더 보기",
      createFailed: "노트를 만들지 못했어요.",
      /** Calendar days since the last edit in the viewer's time zone; 0 or less is today. */
      updated: (days: number) => (days <= 0 ? "오늘" : days === 1 ? "어제" : `${days}일 전`),
    },
    detail: {
      openFailedTitle: "노트를 열지 못했어요",
      openFailedDescription: "노트가 삭제됐거나 네트워크 연결이 끊겼을 수 있어요.",
      backToList: "← 노트 목록",
      backToTrash: "← 휴지통",
      trashedDescription: "이 노트를 복원하면 편집할 수 있어요.",
      restore: "복원",
      purge: "영구 삭제",
      purgeConfirm: "이 노트를 영구 삭제할까요? 되돌릴 수 없어요.",
      pin: "고정",
      unpin: "고정 해제",
      archive: "보관",
      unarchive: "보관 해제",
      moveToTrash: "휴지통으로 이동",
      titleLabel: "노트 제목",
      tags: "태그",
      tagsPlaceholder: "프로젝트, 아이디어",
      aliases: "별칭",
      aliasesPlaceholder: "다른 이름",
      source: "원문",
      edit: "편집",
      preview: "미리보기",
      saved: "저장됨",
      saving: "저장 중…",
      saveFailed: "저장 실패",
      saveFailedDetail: "편집한 내용은 이 화면에 남아 있어요. 네트워크 연결을 확인한 뒤 다시 시도하세요.",
      saveFirst: "변경 내용을 먼저 저장한 뒤 다시 시도하세요.",
      updateFailed: "노트를 변경하지 못했어요.",
      trashBlocked: "변경 내용을 저장하지 못해 휴지통으로 옮기지 않았어요.",
      trashFailed: "노트를 휴지통으로 옮기지 못했어요.",
      restoreFailed: "노트를 복원하지 못했어요.",
      purgeFailed: "노트를 영구 삭제하지 못했어요.",
      attachmentLinkFailed: "첨부파일 링크를 저장하지 못했어요. 노트를 열고 다시 시도하세요.",
      leaveSaveFailed: "노트를 저장하지 못했어요. 노트로 돌아가 다시 시도하세요.",
    },
    editor: {
      hint: "Markdown · [[를 입력해 노트 연결",
      bodyLabel: "노트 본문",
      attach: "첨부",
      attachLabel: "파일 첨부",
      uploadFailed: "파일을 첨부하지 못했어요.",
      /** CodeMirror phrase table: keys are CodeMirror's own English phrases; `$` is its placeholder. */
      phrases: {
        "Find": "찾을 내용",
        "Replace": "바꿀 내용",
        "next": "다음",
        "previous": "이전",
        "all": "모두 선택",
        "match case": "대소문자 구분",
        "regexp": "정규식",
        "by word": "단어 단위",
        "replace": "바꾸기",
        "replace all": "모두 바꾸기",
        "close": "닫기",
        "current match": "현재 일치 항목",
        "on line": "줄",
        "replaced $ matches": "$개 항목을 바꿨어요",
        "replaced match on line $": "$번째 줄의 항목을 바꿨어요",
        "Go to line": "줄로 이동",
        "go": "이동",
        "Control character": "제어 문자",
        "Selection deleted": "선택 영역을 삭제했어요",
        "Completions": "자동 완성",
        "folded code": "접힌 코드",
        "unfold": "펼치기",
        "Folded lines": "접은 줄",
        "Unfolded lines": "펼친 줄",
        "to": "~",
        "Fold line": "줄 접기",
        "Unfold line": "줄 펼치기",
        "Diagnostics": "진단",
        "No diagnostics": "진단 결과가 없어요",
      },
    },
    connections: {
      heading: "연결",
      loadFailed: "연결 정보를 불러오지 못했어요",
      outgoing: "이 노트가 연결한 노트",
      outgoingEmpty: "아직 나가는 링크가 없어요.",
      create: "만들기",
      backlinks: "백링크",
      backlinksEmpty: "아직 이 노트를 연결한 노트가 없어요.",
      unlinked: "연결되지 않은 언급",
      unlinkedEmpty: "일반 텍스트 언급이 없어요.",
      related: "관련 노트",
      relatedEmpty: "텍스트가 비슷한 노트가 없어요.",
      relatedLoading: "관련 노트를 찾는 중…",
      relatedRetry: "다시 불러오기",
    },
    daily: {
      label: "오늘 노트",
      opening: "데일리 노트를 여는 중…",
      openFailed: "데일리 노트를 열지 못했어요",
      preparing: "현지 날짜 기준으로 노트를 준비하고 있어요.",
      openFailedDetail: "네트워크 연결을 확인하고 날짜를 선택해 다시 시도하세요.",
      date: "날짜",
      open: "열기",
    },
  },
  en: {
    loading: "Loading notes…",
    retry: "Try again",
    openLinkFailed: "Couldn't open the linked note.",
    workspace: {
      emptyTitle: "Select a note",
      emptyDescription: "Open a note from the list on the left, or create a new one.",
    },
    list: {
      label: "Note list",
      heading: "Notes",
      tagline: "Connect your thoughts and find them again.",
      newNote: "New note",
      searchLabel: "Search notes",
      searchPlaceholder: "Search titles and content",
      clearSearch: "Clear search",
      viewsLabel: "Note views",
      views: { all: "All", pinned: "Pinned", archived: "Archived", trash: "Trash" },
      tagsFailed: "Couldn't load tags · Try again",
      tagFilter: "Tag",
      allTags: "All tags",
      loadFailedTitle: "Couldn't load notes",
      loadFailedDescription: "Check your connection and try again.",
      trashEmpty: "Trash is empty",
      empty: "No notes to show",
      emptyFiltered: "Try a different search or filter.",
      emptyStart: "Create a note to start writing.",
      pinned: "Pinned",
      loadMore: "Load more",
      createFailed: "Couldn't create a note.",
      updated: (days) => (days <= 0 ? "Today" : days === 1 ? "Yesterday" : `${days} days ago`),
    },
    detail: {
      openFailedTitle: "Couldn't open this note",
      openFailedDescription: "It may have been deleted, or your connection dropped.",
      backToList: "← All notes",
      backToTrash: "← Trash",
      trashedDescription: "Restore this note to edit it.",
      restore: "Restore",
      purge: "Delete permanently",
      purgeConfirm: "Delete this note permanently? This can't be undone.",
      pin: "Pin",
      unpin: "Unpin",
      archive: "Archive",
      unarchive: "Unarchive",
      moveToTrash: "Move to trash",
      titleLabel: "Note title",
      tags: "Tags",
      tagsPlaceholder: "project, idea",
      aliases: "Aliases",
      aliasesPlaceholder: "Other names",
      source: "Source",
      edit: "Edit",
      preview: "Preview",
      saved: "Saved",
      saving: "Saving…",
      saveFailed: "Save failed",
      saveFailedDetail: "Your edits are still here. Check your connection and try again.",
      saveFirst: "Save your changes first, then try again.",
      updateFailed: "Couldn't update the note.",
      trashBlocked: "Couldn't save your changes, so the note wasn't moved to the trash.",
      trashFailed: "Couldn't move the note to the trash.",
      restoreFailed: "Couldn't restore the note.",
      purgeFailed: "Couldn't delete the note permanently.",
      attachmentLinkFailed: "Couldn't save the attachment link. Open the note and try again.",
      leaveSaveFailed: "Couldn't save the note. Go back to it and try again.",
    },
    editor: {
      hint: "Markdown · Type [[ to link a note",
      bodyLabel: "Note body",
      attach: "Attach",
      attachLabel: "Attach a file",
      uploadFailed: "Couldn't attach the file.",
      phrases: {
        "Find": "Find",
        "Replace": "Replace",
        "next": "next",
        "previous": "previous",
        "all": "all",
        "match case": "match case",
        "regexp": "regexp",
        "by word": "by word",
        "replace": "replace",
        "replace all": "replace all",
        "close": "close",
        "current match": "current match",
        "on line": "on line",
        "replaced $ matches": "replaced $ matches",
        "replaced match on line $": "replaced match on line $",
        "Go to line": "Go to line",
        "go": "go",
        "Control character": "Control character",
        "Selection deleted": "Selection deleted",
        "Completions": "Completions",
        "folded code": "folded code",
        "unfold": "unfold",
        "Folded lines": "Folded lines",
        "Unfolded lines": "Unfolded lines",
        "to": "to",
        "Fold line": "Fold line",
        "Unfold line": "Unfold line",
        "Diagnostics": "Diagnostics",
        "No diagnostics": "No diagnostics",
      },
    },
    connections: {
      heading: "Connections",
      loadFailed: "Couldn't load connections",
      outgoing: "Links from this note",
      outgoingEmpty: "No outgoing links yet.",
      create: "Create",
      backlinks: "Backlinks",
      backlinksEmpty: "No notes link here yet.",
      unlinked: "Unlinked mentions",
      unlinkedEmpty: "No plain-text mentions.",
      related: "Related notes",
      relatedEmpty: "No notes with similar text.",
      relatedLoading: "Finding related notes…",
      relatedRetry: "Load again",
    },
    daily: {
      label: "Today's note",
      opening: "Opening daily note…",
      openFailed: "Couldn't open the daily note",
      preparing: "Preparing the note for your local date.",
      openFailedDetail: "Check your connection, choose a date and try again.",
      date: "Date",
      open: "Open",
    },
  },
});
