import { describe, expect, test } from "bun:test";
import { renderToStaticMarkup } from "react-dom/server";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { SOURCE_COMPONENTS } from "@/features/notes/MarkdownPreview";
import { expandWikiLinks } from "@/features/notes/markdown";
import { sourceBlockForLine, sourceEvidence, sourceNoteUrl } from "./source-passage";

const UPDATED = "2026-10-07T06:00:00.000Z";
const passage = { heading: "Repeated heading", startLine: 7, endLine: 12 };

describe("versioned source navigation", () => {
  test("encodes the note ID, source line and saved timestamp", () => {
    const href = sourceNoteUrl("한글 / note", passage, UPDATED);
    const url = new URL(href, "https://irang.invalid");
    expect(url.pathname).toBe("/notes/%ED%95%9C%EA%B8%80%20%2F%20note");
    expect(url.searchParams.get("line")).toBe("7");
    expect(url.searchParams.get("at")).toBe(UPDATED);
  });

  test("opens only the note when location or version evidence is missing", () => {
    expect(sourceNoteUrl("note", undefined, UPDATED)).toBe("/notes/note");
    expect(sourceNoteUrl("note", passage)).toBe("/notes/note");
  });

  test("enables a verified line when timestamp representations refer to the same instant", () => {
    expect(sourceEvidence("7", "2026-10-07T15:00:00+09:00", UPDATED, false, false)).toEqual({
      state: "ready", line: 7, updatedAt: UPDATED,
    });
  });

  test("refuses a moved source even when the local draft is clean", () => {
    expect(sourceEvidence("7", UPDATED, "2026-10-07T06:01:00.000Z", false, false)).toEqual({ state: "stale" });
  });

  test("does not enable line navigation while revalidating or displaying a different draft", () => {
    expect(sourceEvidence("7", UPDATED, UPDATED, false, true)).toEqual({ state: "checking" });
    expect(sourceEvidence("7", UPDATED, UPDATED, true, false)).toEqual({ state: "draft" });
  });

  test("rejects malformed lines and missing or malformed timestamps", () => {
    for (const line of ["", "0", "-1", "1.5", "1e2", "7wrong", "9007199254740992"]) {
      expect(sourceEvidence(line, UPDATED, UPDATED, false, false)).toEqual({ state: "invalid" });
    }
    for (const at of [null, "", "not a timestamp"]) {
      expect(sourceEvidence("7", at, UPDATED, false, false)).toEqual({ state: "invalid" });
    }
    expect(sourceEvidence(null, UPDATED, UPDATED, false, false)).toEqual({ state: "none" });
  });
});

/** Read the anchors generated by the actual preview components and Markdown pipeline. */
function renderedBlocks(body: string) {
  const markup = renderToStaticMarkup(
    <ReactMarkdown remarkPlugins={[remarkGfm]} components={SOURCE_COMPONENTS}>{expandWikiLinks(body)}</ReactMarkdown>,
  );
  return Array.from(markup.matchAll(/<[^/!][^>]*\bdata-source-start="(\d+)"[^>]*>/g), ([tag, start]) => ({
    id: tag.match(/\bid="([^"]+)"/)?.[1],
    startLine: Number(start),
    endLine: Number(tag.match(/\bdata-source-end="(\d+)"/)?.[1]),
  }));
}

describe("rendered source blocks", () => {
  test("duplicate headings have distinct line identities after CRLF and wikilink expansion", () => {
    const body = ["## Same", "", "[[Target|Visible]]", "", "## Same", "", "Other paragraph"].join("\r\n");
    const blocks = renderedBlocks(body);
    expect(blocks.map((block) => block.id)).toEqual([
      "source-line-1-h2", "source-line-3-p", "source-line-5-h2", "source-line-7-p",
    ]);
    expect(new Set(blocks.map((block) => block.id)).size).toBe(blocks.length);
    expect(sourceBlockForLine(blocks, 5, body)?.id).toBe("source-line-5-h2");
  });

  test("an inner line of a long paragraph opens its whole rendered paragraph", () => {
    const body = `## Heading\n\n${"긴 문장 ".repeat(1000)}[[Target]]\ninside the same paragraph\nlast line`;
    const blocks = renderedBlocks(body);
    expect(sourceBlockForLine(blocks, 4, body)).toEqual({ id: "source-line-3-p", startLine: 3, endLine: 5 });
  });

  test("code and setext heading inner lines open their containing block", () => {
    const body = "```ts\nconst value = 1;\nvalue++;\n```\n\nSetext\n------";
    const blocks = renderedBlocks(body);
    expect(sourceBlockForLine(blocks, 3, body)).toEqual({ id: "source-line-1-pre", startLine: 1, endLine: 4 });
    expect(sourceBlockForLine(blocks, 7, body)).toEqual({ id: "source-line-6-h2", startLine: 6, endLine: 7 });
  });

  test("nested list and table locations choose the smallest rendered block", () => {
    const body = "- outer\n  - inner\n\n| A | B |\n| - | - |\n| C | D |";
    const blocks = renderedBlocks(body);
    expect(sourceBlockForLine(blocks, 2, body)?.id).toBe("source-line-2-li");
    expect(sourceBlockForLine(blocks, 6, body)?.id).toBe("source-line-6-tr");
  });

  test("blank separators open the next block while absent rendered content never guesses", () => {
    const body = "first\n\nsecond\n\n<div>hidden</div>";
    const blocks = renderedBlocks(body);
    expect(sourceBlockForLine(blocks, 2, body)?.id).toBe("source-line-3-p");
    expect(sourceBlockForLine(blocks, 5, body)).toBeUndefined();
    expect(sourceBlockForLine(blocks, 99, body)).toBeUndefined();
    expect(sourceBlockForLine(renderedBlocks(""), 1, "")).toBeUndefined();
  });
});
