#!/bin/bash
set -euo pipefail

: "${POSTGRES_APP_USER:?POSTGRES_APP_USER is required}"
: "${POSTGRES_APP_PASSWORD:?POSTGRES_APP_PASSWORD is required}"
: "${POSTGRES_APP_DB:?POSTGRES_APP_DB is required}"

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
  CREATE USER ${POSTGRES_APP_USER} WITH PASSWORD '${POSTGRES_APP_PASSWORD}';
  CREATE DATABASE ${POSTGRES_APP_DB} OWNER ${POSTGRES_APP_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_APP_DB}" <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS vector;
  GRANT ALL ON SCHEMA public TO ${POSTGRES_APP_USER};
EOSQL
