export const HOME_COPY = {
  inboxHeroTitle: "미처리",
  inboxEmptyTitle: "쌓인 캡처가 없어요",
  inboxEmptyBody:
    "생각·링크·메모를 먼저 담아 두세요. 나중에 Inbox에서 노트로 정리합니다.",
  emptyVault: "쌓인 캡처가 없어요",
  capture: "캡처",
  organize: "정리",
  homeError: "불러오지 못했어요 · 다시",
  retry: "다시",
  continuePrefix: "이어서",
  continueMore: "더 보기",
  install: "홈 화면에 추가",
  installDismiss: "나중에",
  installIos: "공유 메뉴에서 홈 화면에 추가할 수 있어요",
  loading: "불러오는 중",
  pagerSearch: "검색",
  pagerHome: "홈",
  pagerChat: "채팅",
} as const;
