export const HOME_COPY = {
  eyebrow: "일요일 · 9월 27일",
  heroTitle: "무엇을 찾을까요?",
  quickCapture: "빠른 캡처",
  startSynth: "합성 시작",
  cmdLabel: "검색 · 커맨드",
  cmdPlaceholder: "노트, 클립, 대화에서 검색하거나 질문하기…",
  cmdPlaceholderEmpty: "첫 노트를 남기거나, 질문을 시작해 보세요…",
  cmdKbd: "⌘ K",
  recentLibrary: "최근 라이브러리",
  viewAll: "전체 보기",
  synthTitle: "합성 · 채팅",
  newChat: "새 대화",
  synthTag: "세컨드 브레인",
  synthIdle:
    "아직 참조할 항목이 없어요. 캡처 한 건만 있어도 요약을 시작할 수 있어요.",
  synthPrompt: "오늘 캡처한 항목을 묶어 볼 수 있어요. 어디부터 볼까요?",
  synthComposer: "이어서 질문하기…",
  statNotes: "전체 노트",
  statInbox: "미처리 수집",
  statGraph: "연결 관계",
  emptyDeskTitle: "책상이 비어 있어요",
  emptyDeskBody:
    "웹 클립, 빠른 메모, 또는 대화를 남겨 두면 검색과 합성이 여기서 시작됩니다.",
  firstCapture: "첫 캡처",
  inboxHeroTitle: "미처리",
  inboxEmptyTitle: "쌓인 캡처가 없어요",
  inboxEmptyBody:
    "생각·링크·메모를 먼저 담아 두세요. 나중에 수집에서 노트로 정리합니다.",
  emptyVault: "책상이 비어 있어요",
  capture: "빠른 캡처",
  organize: "정리",
  homeError: "불러오지 못했어요 · 다시",
  retry: "다시",
  continuePrefix: "이어서",
  continueMore: "더 보기",
  loading: "불러오는 중",
} as const;
