import { defineCopy } from "@/lib/i18n/copy";

const days = (count: number) => (count === 1 ? "1 day left" : `${count} days left`);

/** Settings page copy. The language section reuses LANGUAGE_COPY; AI field copy lives in features/setup. */
export const SETTINGS_COPY = defineCopy({
  ko: {
    title: "설정",
    lead: "화면, 로그인 세션, 선택 기능이 어떻게 동작하는지 확인하고 바꿀 수 있어요.",
    theme: {
      title: "화면",
      description: "이 브라우저에 저장돼서 새로고침하거나 다른 화면으로 가도 그대로예요.",
      legend: "테마",
      system: "시스템",
      light: "밝게",
      dark: "어둡게",
      systemDark: "기기 설정을 따라 지금은 어두운 화면이에요.",
      systemLight: "기기 설정을 따라 지금은 밝은 화면이에요.",
      alwaysDark: "항상 어두운 화면으로 보여요.",
      alwaysLight: "항상 밝은 화면으로 보여요.",
    },
    session: {
      title: "로그인 세션",
      description: "이 기기에서 로그인이 언제까지 유지되는지 보고, 필요하면 로그아웃할 수 있어요.",
      loading: "세션 정보를 불러오는 중",
      loadFailed: "세션 정보를 불러오지 못했어요.",
      loadHint: "네트워크 연결을 확인하세요.",
      reload: "다시 불러오기",
      expiryLabel: "이 기기 로그인 만료",
      expiresToday: "오늘 만료",
      daysLeft: (count: number) => `${count}일 남음`,
      noExpiry: "만료 시각을 확인할 수 없어요.",
      renewNote: "만료되면 비밀번호로 다시 로그인하세요. 로그인할 때마다 기간이 새로 시작돼요.",
      logout: "이 기기에서 로그아웃",
      logoutAll: "모든 기기에서 로그아웃",
      unsavedDrafts: "저장하지 않은 노트 변경 내용이 있어요. 로그아웃할까요?",
      confirmTitle: "모든 기기에서 로그아웃할까요?",
      confirmDescription: "이 기기를 포함해 로그인한 모든 브라우저와 설치한 앱에서 세션이 바로 끊겨요. 다시 쓰려면 기기마다 비밀번호로 로그인해야 해요.",
      cancel: "취소",
      confirm: "모두 로그아웃",
      revokeFailed: "세션을 끊지 못했어요. 다시 시도하세요.",
    },
    ai: {
      title: "AI 기능 (선택)",
      description: "채팅과 인박스 정리에 서로 다른 연결을 쓸 수 있어요. 연결을 저장해도 실제로 쓸 연결은 따로 골라요.",
      loading: "AI 설정을 불러오는 중",
      loadFailed: "AI 설정을 불러오지 못했어요.",
      loadHint: "네트워크 연결을 확인하세요.",
      reload: "다시 불러오기",
      chatStatus: "노트 채팅 상태",
      statusFailed: "확인 실패",
      statusReady: "연결 설정됨",
      statusOff: "설정되지 않음",
      chatTitle: "노트 채팅",
      jevTitle: "인박스 정리 (Jev)",
      chatConsentRequired: "AI 제공자에게 채팅 데이터를 보내는 데 동의해 주세요.",
      jevConsentRequired: "Jev에 캡처 데이터를 보내는 데 동의해 주세요.",
      save: "사용 설정 저장",
      saving: "저장 중…",
      saved: "저장했어요. 새 선택이 바로 적용돼요.",
      deleteTitle: "저장된 연결을 삭제할까요?",
      deleteDescription: "삭제한 키와 로그인 정보는 복구할 수 없어요. 이 연결을 쓰는 AI 기능도 함께 꺼져요.",
      cancel: "취소",
      delete: "연결 삭제",
    },
    purpose: {
      add: "연결 추가",
      active: "사용할 연결",
      off: "사용 안 함",
      environment: "서버 환경 연결",
      offNote: "사용 안 함을 골라도 저장된 연결은 그대로 남아요.",
      inUse: "사용 중",
      selected: "선택됨 · 저장 전",
      stored: "저장됨",
      edit: "편집",
      remove: "삭제",
      empty: "저장된 연결이 없어요. 연결을 추가해도 여기서 선택하기 전에는 쓰지 않아요.",
    },
    dialog: {
      editTitle: "AI 연결 편집",
      addChatTitle: "채팅 연결 추가",
      addJevTitle: "Jev 연결 추가",
      editDescription: "사용 중인 연결은 저장하는 즉시 바뀐 내용이 적용돼요. 사용하지 않는 연결은 따로 선택해야 해요.",
      addDescription: "저장해도 바로 사용되지는 않아요. 목록에서 이 연결을 선택한 뒤 사용 설정을 저장하세요.",
      cancel: "취소",
      save: "연결 저장",
      saving: "저장 중…",
    },
    install: {
      title: "앱으로 설치",
      description: "설치하면 홈 화면이나 작업 표시줄에서 바로 열 수 있어요.",
      standalone: "지금 설치한 앱으로 실행 중이에요.",
      browser: "지금은 브라우저에서 열려 있어요.",
      chromium: "Chrome이나 Edge에서는 주소창의 설치 아이콘이나 메뉴의 ‘앱 설치’를 누르세요.",
      safari: "iPhone과 iPad의 Safari에서는 공유 버튼을 누른 뒤 ‘홈 화면에 추가’를 고르세요.",
      android: (brand: string) => `Android에 설치하면 다른 앱의 공유 메뉴에서 ${brand}을 골라 링크나 글을 인박스로 보낼 수 있어요.`,
      offline: "설치해도 오프라인 저장소는 없어요. 노트를 열고 저장하려면 인터넷에 연결돼 있어야 해요.",
    },
    data: {
      title: "데이터 저장",
      description: "노트가 어디에 저장되는지 알려 드려요.",
      body: "노트, 인박스, 채팅 기록과 첨부파일은 이 앱을 운영하는 서버의 데이터베이스와 저장 폴더에 저장돼요. 브라우저에 따로 암호화해 두는 데이터는 없어요. 이 기기에는 로그인 쿠키와 테마, 사이드바, 언어 설정만 남아요. 전체 백업은 서버에서 관리해요.",
    },
    templates: {
      title: "템플릿",
      description: "자주 쓰는 노트 틀을 저장해 두고 새 노트를 그 틀로 시작해요.",
      help: "본문의 {{date}}는 오늘 날짜로, {{title}}은 새 노트 제목으로 바뀌어요.",
      add: "템플릿 추가",
      listLabel: "저장한 템플릿",
      loading: "템플릿을 불러오는 중",
      loadFailed: "템플릿을 불러오지 못했어요.",
      loadHint: "네트워크 연결을 확인하세요.",
      reload: "다시 불러오기",
      empty: "아직 템플릿이 없어요. 회의록이나 하루 점검처럼 자주 쓰는 틀을 추가해 보세요.",
      emptyBody: "빈 본문",
      dailyBadge: "일일 노트 기본값",
      create: "이 템플릿으로 만들기",
      edit: "편집",
      remove: "삭제",
      addTitle: "템플릿 추가",
      editTitle: "템플릿 편집",
      nameLabel: "이름",
      namePlaceholder: "예: 회의록",
      bodyLabel: "본문 (Markdown)",
      bodyPlaceholder: "## {{date}} 회의\n\n- [ ] 할 일",
      dailyLabel: "일일 노트 기본값",
      dailyHint: "새 데일리 노트를 이 본문으로 시작해요. 기본값은 하나만 둘 수 있어서, 켜면 다른 템플릿의 기본값은 꺼져요. 이미 만든 데일리 노트는 바뀌지 않아요.",
      nameRequired: "이름을 입력하세요.",
      nameTooLong: (max: number) => `이름은 ${max}자까지 쓸 수 있어요.`,
      bodyTooLong: "본문이 너무 길어요. 일부를 줄여 주세요.",
      cancel: "취소",
      save: "템플릿 저장",
      saveFailed: "템플릿을 저장하지 못했어요. 다시 시도하세요.",
      saved: "템플릿을 저장했어요.",
      deleteTitle: (name: string) => `'${name}' 템플릿을 삭제할까요?`,
      deleteDescription: "삭제한 템플릿은 되돌릴 수 없어요. 이 템플릿으로 만든 노트는 그대로 남아요.",
      deleteDefault: "일일 노트 기본값이라서, 삭제하면 새 데일리 노트는 빈 본문으로 시작해요.",
      deleteConfirm: "템플릿 삭제",
      deleteFailed: "템플릿을 삭제하지 못했어요. 다시 시도하세요.",
      deleted: "템플릿을 삭제했어요.",
      createFailed: "노트를 만들지 못했어요. 다시 시도하세요.",
      bodyFailed: "노트는 만들었지만 템플릿 내용을 넣지 못했어요. 노트에서 직접 입력하세요.",
    },
    exportData: {
      title: "내보내기",
      description: "노트를 Markdown 파일로 내려받아요.",
      action: "Markdown으로 내보내기",
      contents: "보관한 노트를 포함한 모든 노트가 YAML 머리말(front matter)이 붙은 .md 파일로, 첨부파일과 함께 zip 하나에 담겨요. 휴지통, 인박스, 채팅, 설정은 들어가지 않아요.",
    },
    shortcuts: {
      title: "키보드 단축키",
      description: "글을 입력하는 중에는 한 글자 단축키가 동작하지 않아요.",
      palette: "명령 팔레트",
      quickOpen: "노트 빠르게 열기",
      capture: "빠르게 캡처",
      search: "검색으로 이동",
      home: "홈으로 이동",
      inbox: "인박스로 이동",
      notes: "노트로 이동",
      tasks: "할 일로 이동",
      graph: "그래프로 이동",
      chat: "채팅으로 이동",
    },
  },
  en: {
    title: "Settings",
    lead: "See and change how the display, your login session and optional features work.",
    theme: {
      title: "Appearance",
      description: "Saved in this browser and kept when you reload or move to another page.",
      legend: "Theme",
      system: "System",
      light: "Light",
      dark: "Dark",
      systemDark: "Following your device, so it's dark right now.",
      systemLight: "Following your device, so it's light right now.",
      alwaysDark: "Always uses the dark theme.",
      alwaysLight: "Always uses the light theme.",
    },
    session: {
      title: "Login session",
      description: "See how long this device stays logged in, and log out when you need to.",
      loading: "Loading session details",
      loadFailed: "Couldn't load session details.",
      loadHint: "Check your network connection.",
      reload: "Reload",
      expiryLabel: "Login on this device expires",
      expiresToday: "Expires today",
      daysLeft: days,
      noExpiry: "The expiry time isn't available.",
      renewNote: "When it expires, log in again with your password. Each login starts a new period.",
      logout: "Log out on this device",
      logoutAll: "Log out on all devices",
      unsavedDrafts: "You have unsaved note changes. Log out anyway?",
      confirmTitle: "Log out on all devices?",
      confirmDescription: "Sessions in every logged-in browser and installed app, including this one, end right away. You'll need your password to log in again on each device.",
      cancel: "Cancel",
      confirm: "Log out everywhere",
      revokeFailed: "Couldn't end the sessions. Try again.",
    },
    ai: {
      title: "AI features (optional)",
      description: "Chat and inbox triage can use different connections. Saving a connection and choosing which one to use are separate steps.",
      loading: "Loading AI settings",
      loadFailed: "Couldn't load AI settings.",
      loadHint: "Check your network connection.",
      reload: "Reload",
      chatStatus: "Note chat status",
      statusFailed: "Check failed",
      statusReady: "Configured",
      statusOff: "Not set up",
      chatTitle: "Note chat",
      jevTitle: "Inbox triage (Jev)",
      chatConsentRequired: "Agree to send chat data to the provider.",
      jevConsentRequired: "Agree to send capture data to Jev.",
      save: "Save usage settings",
      saving: "Saving…",
      saved: "Saved. Your new choices apply right away.",
      deleteTitle: "Delete this saved connection?",
      deleteDescription: "Deleted keys and sign-in details can't be recovered. Any AI feature using this connection turns off too.",
      cancel: "Cancel",
      delete: "Delete connection",
    },
    purpose: {
      add: "Add connection",
      active: "Connection to use",
      off: "Off",
      environment: "Server environment connection",
      offNote: "Choosing Off keeps your saved connections.",
      inUse: "In use",
      selected: "Selected · not saved",
      stored: "Saved",
      edit: "Edit",
      remove: "Delete",
      empty: "No saved connections. A new connection isn't used until you select it here.",
    },
    dialog: {
      editTitle: "Edit AI connection",
      addChatTitle: "Add chat connection",
      addJevTitle: "Add Jev connection",
      editDescription: "Changes to a connection in use apply as soon as you save. If a connection isn't in use, select it separately.",
      addDescription: "Saving doesn't start using it. Select this connection in the list, then save your usage settings.",
      cancel: "Cancel",
      save: "Save connection",
      saving: "Saving…",
    },
    install: {
      title: "Install as an app",
      description: "Install it to open it straight from your home screen or taskbar.",
      standalone: "Running as an installed app.",
      browser: "Running in a browser right now.",
      chromium: "In Chrome or Edge, select the install icon in the address bar, or Install in the browser menu.",
      safari: "In Safari on iPhone and iPad, tap Share, then choose Add to Home Screen.",
      android: (brand) => `Once installed on Android, choose ${brand} from another app's share menu to send links or text to your inbox.`,
      offline: "Installing doesn't add offline storage. You need an internet connection to open and save notes.",
    },
    data: {
      title: "Data storage",
      description: "Where your notes are kept.",
      body: "Notes, inbox items, chat history and attachments are stored in the database and storage folder of the server that runs this app. Nothing is stored encrypted in your browser. This device keeps only the login cookie and your theme, sidebar and language settings. Full backups are managed on the server.",
    },
    templates: {
      title: "Templates",
      description: "Save note outlines you use often and start new notes from them.",
      help: "In the body, {{date}} becomes today's date and {{title}} becomes the new note's title.",
      add: "Add template",
      listLabel: "Saved templates",
      loading: "Loading templates",
      loadFailed: "Couldn't load templates.",
      loadHint: "Check your network connection.",
      reload: "Reload",
      empty: "No templates yet. Add an outline you reuse, like meeting notes or a daily check-in.",
      emptyBody: "Empty body",
      dailyBadge: "Daily note default",
      create: "Create a note",
      edit: "Edit",
      remove: "Delete",
      addTitle: "Add template",
      editTitle: "Edit template",
      nameLabel: "Name",
      namePlaceholder: "e.g. Meeting notes",
      bodyLabel: "Body (Markdown)",
      bodyPlaceholder: "## Meeting on {{date}}\n\n- [ ] Follow up",
      dailyLabel: "Daily note default",
      dailyHint: "New daily notes start with this body. Only one template can be the default, so turning this on turns it off for the others. Existing daily notes don't change.",
      nameRequired: "Enter a name.",
      nameTooLong: (max) => `Names can be up to ${max} characters.`,
      bodyTooLong: "The body is too long. Shorten it and try again.",
      cancel: "Cancel",
      save: "Save template",
      saveFailed: "Couldn't save the template. Try again.",
      saved: "Template saved.",
      deleteTitle: (name) => `Delete "${name}"?`,
      deleteDescription: "You can't undo this. Notes created from this template stay as they are.",
      deleteDefault: "It's the daily note default, so new daily notes will start empty.",
      deleteConfirm: "Delete template",
      deleteFailed: "Couldn't delete the template. Try again.",
      deleted: "Template deleted.",
      createFailed: "Couldn't create the note. Try again.",
      bodyFailed: "Created the note, but couldn't add the template content. Type it in the note instead.",
    },
    exportData: {
      title: "Export",
      description: "Download your notes as Markdown files.",
      action: "Export as Markdown",
      contents: "One zip with every note, archived ones included, as .md files with YAML front matter, plus their attachments. Trash, inbox, chat and settings aren't included.",
    },
    shortcuts: {
      title: "Keyboard shortcuts",
      description: "Single-key shortcuts don't work while you're typing.",
      palette: "Command palette",
      quickOpen: "Quick open note",
      capture: "Quick capture",
      search: "Go to search",
      home: "Go to home",
      inbox: "Go to inbox",
      notes: "Go to notes",
      tasks: "Go to tasks",
      graph: "Go to graph",
      chat: "Go to chat",
    },
  },
});
