import { defineCopy } from "@/lib/i18n/copy";

const days = (count: number) => (count === 1 ? "1 day left" : `${count} days left`);

/** Settings page copy. The language section reuses LANGUAGE_COPY; AI field copy lives in features/setup. */
export const SETTINGS_COPY = defineCopy({
  ko: {
    title: "설정",
    lead: "화면, 로그인 세션, 선택 기능이 어떻게 동작하는지 확인하고 바꿀 수 있어요.",
    theme: {
      title: "화면",
      description: "이 브라우저에 저장되며 새로고침하거나 다른 화면으로 가도 유지돼요.",
      legend: "테마",
      system: "시스템",
      light: "밝게",
      dark: "어둡게",
      systemDark: "기기 설정을 따라 지금은 어두운 화면이에요.",
      systemLight: "기기 설정을 따라 지금은 밝은 화면이에요.",
      alwaysDark: "항상 어두운 화면으로 보여요.",
      alwaysLight: "항상 밝은 화면으로 보여요.",
    },
    session: {
      title: "로그인 세션",
      description: "이 기기의 로그인이 언제까지 유지되는지 확인하고, 필요하면 로그인을 끊을 수 있어요.",
      loading: "세션 정보를 불러오는 중",
      loadFailed: "세션 정보를 불러오지 못했습니다.",
      loadHint: "네트워크 상태를 확인해 주세요.",
      reload: "다시 불러오기",
      expiryLabel: "이 기기의 로그인 만료",
      expiresToday: "오늘 만료",
      daysLeft: (count: number) => `${count}일 남음`,
      noExpiry: "만료 시각을 확인할 수 없어요.",
      renewNote: "만료되면 비밀번호로 다시 로그인하면 돼요. 로그인하면 새 기간이 시작돼요.",
      logout: "이 기기에서 로그아웃",
      logoutAll: "모든 기기에서 로그아웃",
      unsavedDrafts: "저장되지 않은 노트 변경 내용이 있습니다. 로그아웃할까요?",
      confirmTitle: "모든 기기에서 로그아웃할까요?",
      confirmDescription: "이 기기를 포함해 로그인된 모든 브라우저와 설치한 앱의 세션이 즉시 끊겨요. 다시 쓰려면 기기마다 비밀번호로 로그인해야 해요.",
      cancel: "취소",
      confirm: "모두 로그아웃",
      revokeFailed: "세션을 끊지 못했습니다. 다시 시도해 주세요.",
    },
    ai: {
      title: "AI 기능 (선택)",
      description: "채팅과 인박스 정리는 서로 다른 연결을 사용할 수 있어요. 연결을 저장하는 것과 실제 사용 여부는 별도로 관리돼요.",
      loading: "AI 설정을 불러오는 중",
      loadFailed: "AI 설정을 불러오지 못했습니다.",
      loadHint: "네트워크 상태를 확인해 주세요.",
      reload: "다시 불러오기",
      chatStatus: "노트 채팅 상태",
      statusFailed: "확인 실패",
      statusReady: "연결 설정됨",
      statusOff: "설정되지 않음",
      chatTitle: "노트 채팅",
      jevTitle: "인박스 정리 (Jev)",
      chatConsentRequired: "채팅 데이터 전송에 동의해 주세요.",
      jevConsentRequired: "Jev 데이터 전송에 동의해 주세요.",
      save: "사용 설정 저장",
      saving: "저장 중…",
      saved: "저장했어요. 새 선택이 바로 적용돼요.",
      deleteTitle: "저장된 연결을 삭제할까요?",
      deleteDescription: "삭제한 키와 로그인 정보는 복구할 수 없어요. 이 연결을 사용 중이면 해당 AI 기능도 꺼져요.",
      cancel: "취소",
      delete: "연결 삭제",
    },
    purpose: {
      add: "연결 추가",
      active: "사용할 연결",
      off: "사용 안 함",
      environment: "서버 환경 연결",
      offNote: "사용 안 함은 저장된 연결을 삭제하지 않아요.",
      inUse: "사용 중",
      selected: "선택됨 · 저장 전",
      stored: "저장됨",
      edit: "편집",
      remove: "삭제",
      empty: "저장된 연결이 없어요. 연결을 추가해도 직접 선택하기 전에는 사용되지 않아요.",
    },
    dialog: {
      editTitle: "AI 연결 편집",
      addChatTitle: "채팅 연결 추가",
      addJevTitle: "Jev 연결 추가",
      editDescription: "사용 중인 연결의 변경은 저장 즉시 적용돼요. 사용하지 않는 연결은 별도로 선택해야 해요.",
      addDescription: "저장해도 바로 사용되지는 않아요. 목록에서 이 연결을 선택한 뒤 사용 설정을 저장하세요.",
      cancel: "취소",
      save: "연결 저장",
      saving: "저장 중…",
    },
    install: {
      title: "앱으로 설치",
      description: "홈 화면이나 작업 표시줄에서 바로 열 수 있게 설치할 수 있어요.",
      standalone: "지금 설치된 앱으로 실행 중이에요.",
      browser: "지금은 브라우저에서 열려 있어요.",
      chromium: "Chrome이나 Edge에서는 주소창의 설치 아이콘이나 메뉴의 ‘앱 설치’를 누르세요.",
      safari: "iPhone과 iPad의 Safari에서는 공유 버튼을 누른 뒤 ‘홈 화면에 추가’를 고르세요.",
      android: (brand: string) => `Android에 설치하면 다른 앱의 공유 메뉴에서 ${brand}을 골라 링크나 글을 인박스로 보낼 수 있어요.`,
      offline: "설치해도 오프라인 저장소는 없어요. 인터넷에 연결되어 있어야 노트를 열고 저장할 수 있어요.",
    },
    data: {
      title: "데이터 보관",
      description: "노트가 어디에 저장되는지 알려 드려요.",
      body: "노트, 인박스, 채팅 기록과 첨부 파일은 이 앱을 운영하는 서버의 데이터베이스와 저장 폴더에 저장돼요. 브라우저에 따로 암호화해 보관하지 않으며, 이 기기에는 로그인 쿠키와 테마, 사이드바, 언어 설정만 남아요. 백업과 내보내기는 서버에서 관리해요.",
    },
    shortcuts: {
      title: "키보드 단축키",
      description: "글을 입력하는 중에는 한 글자 단축키가 동작하지 않아요.",
      palette: "명령 팔레트",
      quickOpen: "노트 빠르게 열기",
      capture: "빠르게 캡처",
      search: "검색으로 이동",
      home: "홈으로 이동",
      inbox: "인박스로 이동",
      notes: "노트로 이동",
      graph: "그래프로 이동",
      chat: "채팅으로 이동",
    },
  },
  en: {
    title: "Settings",
    lead: "See and change how the display, your login session and optional features work.",
    theme: {
      title: "Appearance",
      description: "Saved in this browser and kept when you reload or move to another page.",
      legend: "Theme",
      system: "System",
      light: "Light",
      dark: "Dark",
      systemDark: "Following your device, so it's dark right now.",
      systemLight: "Following your device, so it's light right now.",
      alwaysDark: "Always shown in dark.",
      alwaysLight: "Always shown in light.",
    },
    session: {
      title: "Login session",
      description: "See how long this device stays logged in, and log out when you need to.",
      loading: "Loading session details",
      loadFailed: "Couldn't load session details.",
      loadHint: "Check your network connection.",
      reload: "Reload",
      expiryLabel: "Login on this device expires",
      expiresToday: "Expires today",
      daysLeft: days,
      noExpiry: "The expiry time isn't available.",
      renewNote: "When it expires, just log in again with your password. Each login starts a new period.",
      logout: "Log out on this device",
      logoutAll: "Log out on all devices",
      unsavedDrafts: "You have unsaved note changes. Log out anyway?",
      confirmTitle: "Log out on all devices?",
      confirmDescription: "Sessions in every logged-in browser and installed app, including this one, end right away. You'll need your password to log in again on each device.",
      cancel: "Cancel",
      confirm: "Log out everywhere",
      revokeFailed: "Couldn't end the sessions. Try again.",
    },
    ai: {
      title: "AI features (optional)",
      description: "Chat and inbox triage can use different connections. Saving a connection and actually using it are managed separately.",
      loading: "Loading AI settings",
      loadFailed: "Couldn't load AI settings.",
      loadHint: "Check your network connection.",
      reload: "Reload",
      chatStatus: "Note chat status",
      statusFailed: "Check failed",
      statusReady: "Configured",
      statusOff: "Not set up",
      chatTitle: "Note chat",
      jevTitle: "Inbox triage (Jev)",
      chatConsentRequired: "Agree to send chat data to the provider.",
      jevConsentRequired: "Agree to send capture data to Jev.",
      save: "Save usage settings",
      saving: "Saving…",
      saved: "Saved. Your new choices apply right away.",
      deleteTitle: "Delete this saved connection?",
      deleteDescription: "Deleted keys and sign-in details can't be recovered. If this connection is in use, that AI feature turns off too.",
      cancel: "Cancel",
      delete: "Delete connection",
    },
    purpose: {
      add: "Add connection",
      active: "Connection to use",
      off: "Off",
      environment: "Server environment connection",
      offNote: "Turning it off doesn't delete saved connections.",
      inUse: "In use",
      selected: "Selected · not saved",
      stored: "Saved",
      edit: "Edit",
      remove: "Delete",
      empty: "No saved connections. A new connection isn't used until you select it here.",
    },
    dialog: {
      editTitle: "Edit AI connection",
      addChatTitle: "Add chat connection",
      addJevTitle: "Add Jev connection",
      editDescription: "Changes to a connection in use apply as soon as you save. A connection that isn't in use has to be selected separately.",
      addDescription: "Saving doesn't start using it. Select this connection in the list, then save your usage settings.",
      cancel: "Cancel",
      save: "Save connection",
      saving: "Saving…",
    },
    install: {
      title: "Install as an app",
      description: "Install it to open it straight from your home screen or taskbar.",
      standalone: "Running as an installed app.",
      browser: "Open in a browser right now.",
      chromium: "In Chrome or Edge, select the install icon in the address bar, or Install in the browser menu.",
      safari: "In Safari on iPhone and iPad, tap Share, then choose Add to Home Screen.",
      android: (brand) => `Once installed on Android, choose ${brand} from another app's share menu to send links or text to your inbox.`,
      offline: "Installing doesn't add offline storage. You need an internet connection to open and save notes.",
    },
    data: {
      title: "Data storage",
      description: "Where your notes are kept.",
      body: "Notes, inbox items, chat history and attachments are stored in the database and storage folder of the server that runs this app. Nothing is kept separately encrypted in your browser; this device holds only the login cookie and your theme, sidebar and language settings. Backups and exports are managed on the server.",
    },
    shortcuts: {
      title: "Keyboard shortcuts",
      description: "Single-key shortcuts don't work while you're typing.",
      palette: "Command palette",
      quickOpen: "Quick open note",
      capture: "Quick capture",
      search: "Go to search",
      home: "Go to home",
      inbox: "Go to inbox",
      notes: "Go to notes",
      graph: "Go to graph",
      chat: "Go to chat",
    },
  },
});
