import { defineCopy } from "@/lib/i18n/copy";

/**
 * Inbox list, triage editor and shared source/kind labels. Labels are display-only:
 * stored sources, suggested kind ids, tags, titles and bodies stay untranslated.
 */
export const INBOX_COPY = defineCopy({
  ko: {
    title: "인박스",
    intro: "캡처를 검토해 노트로 만들거나 버리세요.",
    remaining: (count: number) => `${count}개 남음`,
    loadError: {
      title: "인박스를 불러오지 못했어요.",
      help: "네트워크 연결을 확인하세요.",
      retry: "다시 불러오기",
    },
    loading: "인박스를 불러오는 중",
    emptyTitle: "인박스가 비어 있어요.",
    emptyDescription: "새 생각이나 링크를 캡처하면 여기에 모여요.",
    listLabel: "인박스 항목",
    views: { label: "인박스 보기", open: "받은 항목", later: "나중에" },
    hints: { move: "이동", open: "열기", promote: "노트 만들기", discard: "버리기", merge: "합치기", snooze: "미루기" },
    noContent: "내용 없음",
    badge: {
      urlPending: "URL 불러오는 중",
      urlFailed: "URL 불러오기 실패",
      suggestionsReady: "제안 준비됨",
    },
    backToList: "← 인박스 목록",
    noSelectionTitle: "검토할 항목을 선택하세요.",
    noSelectionDescription: "목록에서 항목을 선택하면 내용을 고쳐 노트로 만들 수 있어요.",
    toast: {
      promoted: "노트로 만들었어요.",
      promoteFailed: "노트로 만들지 못했어요.",
      discarded: "인박스에서 버렸어요.",
      discardFailed: "항목을 버리지 못했어요.",
      undo: "되돌리기",
      undoFailed: "되돌리지 못했어요.",
      snoozed: (time: string) => `${time}까지 미뤘어요.`,
      broughtBack: "인박스로 돌려놨어요.",
      bringBackFailed: "인박스로 돌리지 못했어요.",
      merged: (title: string) => `'${title}'에 합쳤어요.`,
      openNote: "노트 열기",
      suggestFailed: "제안을 확인하지 못했어요.",
    },
    later: {
      listLabel: "미룬 항목",
      returns: (time: string) => `${time}에 돌아와요`,
      bringBack: "지금 보기",
      emptyTitle: "미룬 항목이 없어요.",
      emptyDescription: "항목을 미루면 정한 시간에 받은 항목으로 돌아와요.",
    },
    snooze: {
      title: "다시 볼 시간",
      presets: { evening: "오늘 저녁", tomorrow: "내일 아침", nextMonday: "다음 주 월요일" },
      custom: "직접 선택",
      customLabel: "날짜와 시간",
      customHint: (time: string) => `${time}에 다시 보여요.`,
      submit: "미루기",
      invalid: "날짜와 시간을 입력하세요.",
      past: "미룰 시간은 지금보다 뒤여야 해요.",
      tooFar: "최대 1년 뒤까지만 미룰 수 있어요.",
      failed: "항목을 미루지 못했어요.",
    },
    merge: {
      title: "노트에 합치기",
      description: "이 캡처를 기존 노트 끝에 덧붙여요.",
      searchLabel: "합칠 노트",
      searchPlaceholder: "제목이나 별칭으로 검색",
      resultsLabel: "노트 검색 결과",
      suggested: "Jev 제안",
      alias: (alias: string) => `별칭: ${alias}`,
      searching: "찾는 중…",
      noResults: "일치하는 노트가 없어요.",
      searchFailed: "노트를 찾지 못했어요. 네트워크 연결을 확인하세요.",
      previewLabel: "덧붙일 내용",
      editedHint: "여기서 고친 내용은 반영되지 않아요. 캡처 원문을 그대로 덧붙여요.",
      cancel: "닫기",
      confirm: "합치기",
      failed: "노트에 합치지 못했어요.",
    },
    editor: {
      openSource: "원문 열기",
      titleLabel: "노트 제목",
      titleRequired: "제목을 입력하세요.",
      bodyLabel: "본문",
      urlPending: "원문 내용을 가져오는 중이에요. 지금 노트로 만들면 현재 본문만 저장돼요.",
      urlFailed: "원문 내용을 가져오지 못했어요. 링크는 노트에 그대로 남아요.",
      tagsLabel: "태그 (선택)",
      tagsPlaceholder: "쉼표로 구분하세요.",
      appliedTags: "적용할 태그",
      discard: "버리기",
      snooze: "미루기",
      merge: "합치기",
      mergeSuggested: "이 노트에 합치기",
      promote: "노트로 만들고 열기",
    },
    suggestions: {
      title: "정리 제안",
      hint: "선택한 제안만 노트에 반영돼요.",
      recheck: "다시 확인",
      pending: "제안이 아직 준비되지 않았어요.",
      unavailable: "AI를 설정하지 않아 제안을 만들 수 없어요. 캡처와 노트 만들기는 그대로 쓸 수 있어요.",
      openSettings: "AI 설정 열기",
      failed: "제안을 만들지 못했어요. 직접 정리하거나 다시 시도하세요.",
      noTags: "추천할 태그가 없어요.",
      kind: "분류 제안:",
      duplicate: "비슷한 기존 노트:",
    },
    kind: { idea: "아이디어", reference: "참고 자료", task: "할 일", other: "기타" },
    source: { web: "직접 입력", url: "링크", share: "공유", api: "API" },
    justNow: "방금",
  },
  en: {
    title: "Inbox",
    intro: "Review each capture, then turn it into a note or discard it.",
    remaining: (count) => `${count} left`,
    loadError: {
      title: "Couldn't load your inbox.",
      help: "Check your network connection.",
      retry: "Try again",
    },
    loading: "Loading inbox",
    emptyTitle: "Your inbox is empty.",
    emptyDescription: "Thoughts and links you capture will collect here.",
    listLabel: "Inbox items",
    views: { label: "Inbox view", open: "Open", later: "Later" },
    hints: { move: "Move", open: "Open", promote: "Create note", discard: "Discard", merge: "Merge", snooze: "Snooze" },
    noContent: "No content",
    badge: {
      urlPending: "Fetching URL",
      urlFailed: "Couldn't fetch URL",
      suggestionsReady: "Suggestions ready",
    },
    backToList: "← Back to inbox",
    noSelectionTitle: "Select an item to review.",
    noSelectionDescription: "Pick an item from the list to edit it and turn it into a note.",
    toast: {
      promoted: "Note created.",
      promoteFailed: "Couldn't create the note.",
      discarded: "Discarded from your inbox.",
      discardFailed: "Couldn't discard the item.",
      undo: "Undo",
      undoFailed: "Couldn't undo that.",
      snoozed: (time) => `Snoozed until ${time}.`,
      broughtBack: "Moved back to your inbox.",
      bringBackFailed: "Couldn't move the item back.",
      merged: (title) => `Merged into "${title}".`,
      openNote: "Open note",
      suggestFailed: "Couldn't check for suggestions.",
    },
    later: {
      listLabel: "Snoozed items",
      returns: (time) => `Returns ${time}`,
      bringBack: "Bring back",
      emptyTitle: "Nothing snoozed.",
      emptyDescription: "Snooze an item and it comes back to Open at the time you pick.",
    },
    snooze: {
      title: "Snooze until",
      presets: { evening: "This evening", tomorrow: "Tomorrow morning", nextMonday: "Next Monday" },
      custom: "Pick a time",
      customLabel: "Date and time",
      customHint: (time) => `Comes back ${time}.`,
      submit: "Snooze",
      invalid: "Enter a date and time.",
      past: "Pick a time in the future.",
      tooFar: "You can snooze for up to a year.",
      failed: "Couldn't snooze the item.",
    },
    merge: {
      title: "Merge into a note",
      description: "Adds this capture to the end of an existing note.",
      searchLabel: "Note to merge into",
      searchPlaceholder: "Search by title or alias",
      resultsLabel: "Matching notes",
      suggested: "Suggested by Jev",
      alias: (alias) => `Alias: ${alias}`,
      searching: "Searching…",
      noResults: "No matching notes.",
      searchFailed: "Couldn't search notes. Check your network connection.",
      previewLabel: "What gets added",
      editedHint: "Your edits here aren't included. The original capture is added as is.",
      cancel: "Cancel",
      confirm: "Merge",
      failed: "Couldn't merge into the note.",
    },
    editor: {
      openSource: "Open original",
      titleLabel: "Note title",
      titleRequired: "Enter a title.",
      bodyLabel: "Body",
      urlPending: "Still fetching the page content. If you create the note now, only the current body is saved.",
      urlFailed: "Couldn't fetch the page content. The link stays in the note.",
      tagsLabel: "Tags (optional)",
      tagsPlaceholder: "Separate tags with commas.",
      appliedTags: "Tags to apply",
      discard: "Discard",
      snooze: "Snooze",
      merge: "Merge",
      mergeSuggested: "Merge into this note",
      promote: "Create note and open",
    },
    suggestions: {
      title: "Suggestions",
      hint: "Only the suggestions you select go into the note.",
      recheck: "Check again",
      pending: "Suggestions aren't ready yet.",
      unavailable: "AI isn't set up, so there are no suggestions. Capturing and creating notes still work.",
      openSettings: "Open AI settings",
      failed: "Couldn't generate suggestions. Sort this one yourself or try again.",
      noTags: "No tags to suggest.",
      kind: "Suggested type:",
      duplicate: "Similar existing note:",
    },
    kind: { idea: "Idea", reference: "Reference", task: "Task", other: "Other" },
    source: { web: "Typed", url: "Link", share: "Shared", api: "API" },
    justNow: "just now",
  },
});
