import { defineCopy } from "@/lib/i18n/copy";

/**
 * Inbox list, triage editor and shared source/kind labels. Labels are display-only:
 * stored sources, suggested kind ids, tags, titles and bodies stay untranslated.
 */
export const INBOX_COPY = defineCopy({
  ko: {
    title: "인박스",
    eyebrow: "정리할 곳",
    intro: "캡처를 검토해 노트로 만들거나 버리세요.",
    remaining: (count: number) => `${count}개 남음`,
    loadError: {
      title: "인박스를 불러오지 못했어요.",
      help: "네트워크 연결을 확인하세요.",
      retry: "다시 불러오기",
    },
    loading: "인박스를 불러오는 중",
    emptyTitle: "인박스가 비어 있어요.",
    emptyDescription: "새 생각이나 링크를 캡처하면 여기에 모여요.",
    listLabel: "인박스 항목",
    noContent: "내용 없음",
    badge: {
      urlPending: "URL 불러오는 중",
      urlFailed: "URL 불러오기 실패",
      suggestionsReady: "제안 준비됨",
    },
    backToList: "← 인박스 목록",
    noSelectionTitle: "검토할 항목을 선택하세요.",
    noSelectionDescription: "목록에서 항목을 선택하면 내용을 고쳐 노트로 만들 수 있어요.",
    discardDialog: {
      title: "이 캡처를 버릴까요?",
      description: "인박스에서 사라지고 되돌릴 수 없어요.",
      cancel: "취소",
      confirm: "버리기",
    },
    toast: {
      promoted: "노트로 만들었어요.",
      promoteFailed: "노트로 만들지 못했어요.",
      discarded: "인박스에서 버렸어요.",
      discardFailed: "항목을 버리지 못했어요.",
      suggestFailed: "제안을 확인하지 못했어요.",
    },
    editor: {
      openSource: "원문 열기",
      titleLabel: "노트 제목",
      titleRequired: "제목을 입력하세요.",
      bodyLabel: "본문",
      urlPending: "원문 내용을 가져오는 중이에요. 지금 노트로 만들면 현재 본문만 저장돼요.",
      urlFailed: "원문 내용을 가져오지 못했어요. 링크는 노트에 그대로 남아요.",
      tagsLabel: "태그 (선택)",
      tagsPlaceholder: "쉼표로 구분하세요.",
      appliedTags: "적용할 태그",
      discard: "버리기",
      promote: "노트로 만들고 열기",
    },
    suggestions: {
      title: "정리 제안",
      hint: "선택한 제안만 노트에 반영돼요.",
      recheck: "다시 확인",
      pending: "제안이 아직 준비되지 않았어요.",
      unavailable: "AI를 설정하지 않아 제안을 만들 수 없어요. 캡처와 노트 만들기는 그대로 쓸 수 있어요.",
      failed: "제안을 만들지 못했어요. 직접 정리하거나 다시 시도하세요.",
      noTags: "추천할 태그가 없어요.",
      kind: "분류 제안:",
      duplicate: "비슷한 기존 노트:",
    },
    kind: { idea: "아이디어", reference: "참고 자료", task: "할 일", other: "기타" },
    source: { web: "직접 입력", url: "링크", share: "공유", api: "API" },
    justNow: "방금",
  },
  en: {
    title: "Inbox",
    eyebrow: "To review",
    intro: "Review each capture, then turn it into a note or discard it.",
    remaining: (count) => `${count} left`,
    loadError: {
      title: "Couldn't load your inbox.",
      help: "Check your network connection.",
      retry: "Try again",
    },
    loading: "Loading inbox",
    emptyTitle: "Your inbox is empty.",
    emptyDescription: "Thoughts and links you capture will collect here.",
    listLabel: "Inbox items",
    noContent: "No content",
    badge: {
      urlPending: "Fetching URL",
      urlFailed: "Couldn't fetch URL",
      suggestionsReady: "Suggestions ready",
    },
    backToList: "← Back to inbox",
    noSelectionTitle: "Select an item to review.",
    noSelectionDescription: "Pick an item from the list to edit it and turn it into a note.",
    discardDialog: {
      title: "Discard this capture?",
      description: "This removes it from your inbox and can't be undone.",
      cancel: "Cancel",
      confirm: "Discard",
    },
    toast: {
      promoted: "Note created.",
      promoteFailed: "Couldn't create the note.",
      discarded: "Discarded from your inbox.",
      discardFailed: "Couldn't discard the item.",
      suggestFailed: "Couldn't check for suggestions.",
    },
    editor: {
      openSource: "Open original",
      titleLabel: "Note title",
      titleRequired: "Enter a title.",
      bodyLabel: "Body",
      urlPending: "Still fetching the page content. If you create the note now, only the current body is saved.",
      urlFailed: "Couldn't fetch the page content. The link stays in the note.",
      tagsLabel: "Tags (optional)",
      tagsPlaceholder: "Separate tags with commas.",
      appliedTags: "Tags to apply",
      discard: "Discard",
      promote: "Create note and open",
    },
    suggestions: {
      title: "Suggestions",
      hint: "Only the suggestions you select go into the note.",
      recheck: "Check again",
      pending: "Suggestions aren't ready yet.",
      unavailable: "AI isn't set up, so there are no suggestions. Capturing and creating notes still work.",
      failed: "Couldn't generate suggestions. Sort this one yourself or try again.",
      noTags: "No tags to suggest.",
      kind: "Suggested type:",
      duplicate: "Similar existing note:",
    },
    kind: { idea: "Idea", reference: "Reference", task: "Task", other: "Other" },
    source: { web: "Typed", url: "Link", share: "Shared", api: "API" },
    justNow: "just now",
  },
});
