\set ON_ERROR_STOP on
\getenv app_password POSTGRES_APP_PASSWORD

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE ROLE second_brain LOGIN PASSWORD :'app_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT CONNECT, TEMPORARY ON DATABASE second_brain TO second_brain;
GRANT USAGE, CREATE ON SCHEMA public TO second_brain;
