export const SEARCH_COPY = {
  title: "검색",
  placeholder: "노트, 클립, 대화에서 검색하거나 질문하기…",
  idleHint: "제목·경로·본문 단어를 입력해 주세요",
  filter: "필터",
  filterApply: "적용",
  filterType: "상태",
  filterAll: "전체",
  filterDraft: "초안",
  filterConfirmed: "확정",
  filterArchived: "보관",
  filterFrom: "시작",
  filterTo: "끝",
  submit: "검색",
  empty: "결과가 없어요 · 단어를 바꿔 보세요",
  indexing: "인덱싱 중 · 키워드만 우선",
  searchFail: "검색에 실패했어요",
  retry: "다시",
  evidenceCta: "선택한 근거로 채팅",
  similar: "유사",
  similarNotes: "유사 노트",
  relevance: "근거",
  routeLead: "이 요청",
  routeChat: "채팅",
  routeSearch: "검색",
  routeInbox: "Inbox",
  pickEvidence: "근거로 선택",
  on: "ON",
  detailEmpty: "결과에서 항목을 고르면 본문이 여기에 표시됩니다",
  detailNoSnippet: "미리보기가 없습니다",
  detailTypeNote: "노트",
} as const;
